spring:
  application:
    name: SpringCore
  jwt:
    secret: ${SPRING_JWT_SECRET}
    access-token-expiration-ms: 900000 # 15m
    refresh-token-expiration-ms: 604800000 # 7d
  profiles:
    active: dev