spring:
  application:
    name: SpringCore
  jwt:
    secret: ${SPRING_JWT_SECRET}
    access-token-expiration-ms: 900000 # 15m
    refresh-token-expiration-ms: 604800000 # 7d
  profiles:
    active: dev
  jpa:
    open-in-view: false

rate-limit:
  capacity: 5
  refill-tokens: 100
  refill-duration-minutes: 1
  cache-expire-hours: 2

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
